all:
	mkdir -p output_report
	pdflatex -interaction nonstopmode --output-directory output_report josepalos_pac4.tex
	pdflatex -interaction nonstopmode --output-directory output_report josepalos_pac4.tex
	mv output_report/josepalos_pac4.pdf josepalos_pac4.pdf
